title: "フーリエ解析と計算機"
summary: |-
  フーリエ解析とは、複雑な関数や現象を三角関数で表せる簡単な波に分解して表現する手法である。
  本書では、はじめに、フーリエ解析の中でも基本となるフーリエ級数、複素フーリエ級数、フーリエ変換、離散時間フーリエ変換、離散フーリエ変換の数学的な導出を行う。
  つぎに、離散フーリエ変換を計算機で高速に計算する手法である高速フーリエ変換と高速フーリエ変換を改善したSplit-Radix FFTの導出を行う。
  最後に、高速フーリエ変換がデジタル信号処理の分野において、どのような役割を持つかを述べる。

  pdf版
  https://a3geek.booth.pm/items/2947447
topics:
  - "math"
published: true
price: 0
toc_depth: 2
allow_override: true
chapters:
  - "b1a70e"
  - "aa4a34"
  - "2618f2"
  - "6d1f49"
  - "6bd00d"
  - "4bfa60"